<!DOCTYPE html>
<html lang="fr">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<title>Music Video of the Day</title>
    <link rel="stylesheet" href="style.css">
	<link href="https://fonts.googleapis.com/css?family=Aldrich|Audiowide" rel="stylesheet"> 
</head>
<body>
	<h1><a href="index.php" >MUSIC VIDEO OF THE DAY</a></H1>
	
	
	<h2 id="yesterday">Browse by:</h2>
	<div id="browse">
		<h3 onclick="myFunction(event)" class="dropbtn resultTitle" id="artistRT">Artist</h3>

		<ul id="myDropdown1" class="dropdown-content">
			<?php  foreach($ArtistsUnique as $artist): ?>
			<li>

					<a href="mv.php?Artist=<?=urlencode($artist);?>"><?= $artist; ?></a>

			</li>
			<?php endforeach; ?>
		</ul>

		<h3 onclick="myFunction(event)" class="dropbtn resultTitle" id="titleRT">Title</h3>

		<div id="myDropdown2" class="dropdown-content">
		<div id="titleResultContainer">
			<ul>
				<?php  foreach($Titles as $title): ?>
				<li>

						<a href="prevIndex.php?clipId=<?= $title['Id']; ?>" id="titleResultTitle"><?= $title['Title']; ?></a>

				</li>

				<?php endforeach; ?>
			</ul>
			<ul>
				<?php  foreach($Titles as $title): ?>
				<li>

						<a href="prevIndex.php?clipId=<?= $title['Id']; ?>"><span> by </span></a>

				</li>

				<?php endforeach; ?>
			</ul>
			<ul>
				<?php  foreach($Titles as $title): ?>
				<li>

						<a href="prevIndex.php?clipId=<?= $title['Id']; ?>" id="titleResultArtist"><?= $title['Artist']; ?></a>

				</li>

				<?php endforeach; ?>
			</ul>
		</div>	
		</div>

		<h3 onclick="myFunction(event)" class="dropbtn resultTitle" id="directorRT">Director</h3>

		<ul id="myDropdown3" class="dropdown-content">
			<?php  foreach($DirectorsUnique as $director): ?>
			<li>

					<a href="mv.php?Director=<?=urlencode($director);?>"><?= $director; ?></a>

			</li>
			<?php endforeach; ?>
		</ul>
	</div>
	
	
	
	<div id="footer">
		<a id="home" href="index.php">HOME</a>
		<a id="webdev" href="http://www.webdevrem.fr/">@WebDevRem</a>
	</div>
	<script>
		function myFunction(event) {
			console.log(event.target);

			if (event.target == document.getElementById("artistRT")) {
				document.getElementById("myDropdown1").classList.toggle("show");
				document.getElementById("myDropdown2").classList.remove("show");
				document.getElementById("myDropdown3").classList.remove("show");
			}
			else if (event.target == document.getElementById("titleRT")) {
				document.getElementById("myDropdown2").classList.toggle("show");
				document.getElementById("myDropdown1").classList.remove("show");
				document.getElementById("myDropdown3").classList.remove("show");				
				
			}			
			else if (event.target == document.getElementById("directorRT")) {
				document.getElementById("myDropdown3").classList.toggle("show");
				document.getElementById("myDropdown2").classList.remove("show");
				document.getElementById("myDropdown1").classList.remove("show");				
				
			}			
		}
		
		function myFunction2() {
			document.getElementById("myDropdown2").classList.add("show");
		}

		function myFunction3() {
			document.getElementById("myDropdown3").classList.add("show");
		}
/*
		window.onclick = function(event) {
			console.log(event);
			if (!event.target.matches('.dropbtn')) {
				var dropdowns = document.getElementsByClassName("dropdown-content");
				var i;
				for (i = 0; i < dropdowns.length; i++) {
					var openDropdown = dropdowns[i];
					if (openDropdown.classList.contains('show')) {
					openDropdown.classList.remove('show');
					}
				}
			}
		} */
	</script>
</body>
</html>		