
	
	<div id="menu">
		<a id="yesterday" class ="menu" href="index.php?clipId=<?= $prevClip; ?>">Previous</a>
		<p id="artist" class ="menu"> <?= $clip['Artist']; ?></p>
		<p id="title" class ="menu"> <?= $clip['Title']; ?></p>
		<p id="director" class ="menu"> <?= $clip['Director']; ?> </p>
		<p id="year" class ="menu"> <?= $clip['Year']; ?> </p>
		<a id="more" class ="menu" href="index.php?p=more">More </a>
	</div>

	<?= $clip['Link']; ?>
