<!DOCTYPE html>
<html lang="fr">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<title>Music Video of the Day</title>
    <link rel="stylesheet" href="css/style.css">
	<link href="https://fonts.googleapis.com/css?family=Aldrich|Audiowide" rel="stylesheet"> 
</head>
<body>
	<h1><a href="index.php">MUSIC VIDEO OF THE DAY</a></H1>
	
	<?php include $page.'.phtml'; ?>

	
	<div id="footer">
		<a id="home" href="index.php">HOME</a>
		<a id="webdev" href="#">@WebDevRem</a>
	</div>
    
    
    <script src="js/main.js"></script>
</body>
</html>	