<!DOCTYPE html>
<html lang="fr">
<head>
	
	<h2 id="yesterday">Browse by:</h2>
	<div id="browse">
		<h3 onclick="myFunction(event)" class="dropbtn resultTitle" id="artistRT">Artist</h3>

		<ul id="myDropdown1" class="dropdown-content">
			<?php  foreach($Artists as $artist): ?>
			<li>

					<a href="index.php?p=more&Artist=<?=urlencode($artist['Artist']);?>"><?= $artist['Artist']; ?></a>

			</li>
			<?php endforeach; ?>
		</ul>

		<h3 onclick="myFunction(event)" class="dropbtn resultTitle" id="titleRT">Title</h3>

		<div id="myDropdown2" class="dropdown-content">
		<div id="titleResultContainer">
			<ul id="titleList">
				<?php  foreach($Titles as $title): ?>
				<li>

						<a href="index.php?clipId=<?= $title['Id']; ?>" class="titleResultTitle <?= 'id'.$title['Id']; ?>" data-id='<?= $title['Id']; ?>' onmouseenter='matchHoverColor(event, "artistList")' onmouseleave='setOriginalColor(event, "artistList")'><?= $title['Title']; ?></a>

				</li>

				<?php endforeach; ?>
			</ul>
			<ul>
				<?php  foreach($Titles as $title): ?>
				<li>

						<a href="index.php?clipId=<?= $title['Id']; ?>"><span> by </span></a>

				</li>

				<?php endforeach; ?>
			</ul>
			<ul id="artistList">
				<?php  foreach($Titles as $title): ?>
				<li>

						<a href="index.php?clipId=<?= $title['Id']; ?>" class="titleResultArtist <?= 'id'.$title['Id']; ?>" data-id='<?= $title['Id']; ?>' onmouseenter='matchHoverColor(event, "titleList")' onmouseleave='setOriginalColor(event, "titleList")'><?= $title['Artist']; ?></a>

				</li>

				<?php endforeach; ?>
			</ul>
		</div>	
		</div>

		<h3 onclick="myFunction(event)" class="dropbtn resultTitle" id="directorRT">Director</h3>

		<ul id="myDropdown3" class="dropdown-content">
			<?php  foreach($Directors as $director): ?>
			<li>

					<a href="index.php?p=more&Director=<?=urlencode($director['Director']);?>"><?= $director['Director']; ?></a>

			</li>
			<?php endforeach; ?>
		</ul>
	</div>
	